[package]
name = "example"
version = "0.1.0"
edition = "2024"


[[test]]
name = "itest"
path = "itest/main.rs"
harness = false

[dependencies]
itest_runner = { path = "../runner" }
testcontainers = { version = "0.25.0", features = ["blocking"] }
