[package]
name = "itest_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
itest_macros = { path = "../macros" }
humantime = "2.2.0"
inventory = "0.3.21"
libtest-mimic = "0.8.1"


testcontainers = { version = "0.25.0", features = ["blocking"] }

[features]
# default = ["testcontainers"]
